### ISSUE TITLE
listCPO() only displays 6 lines

### ISSUE THREAD

**Issue by vapniks** [mlr-org/mlrCPO#40]
```
> listCPO()
                     name               cponame category               subcategory
11       cpoDropConstants             dropconst     data                   cleanup
36          cpoFixFactors            fixfactors     data                   cleanup
10        cpoCollapseFact         collapse.fact     data factor data preprocessing
4            cpoAsNumeric            as.numeric     data        feature conversion
15         cpoDummyEncode           dummyencode     data        feature conversion
13 cpoImpactEncodeClassif impact.encode.classif     data        feature conversion
... (#rows: 69, #cols: 4)
```
How can I get `listCPO()` to display more lines each time?

**Comment by mb706** [comment]
The output of `listCPO()` is a `data.frame` with an additional class that changes the `print` function. You can either use `print(listCPO(), n = [lines to print])`, or convert the result to a data.frame: `as.data.frame(listCPO())` (this also gives the `description` column, which is hidden otherwise). This does not change the data per se, only the printed output.

The documentation of this is very pood, and I will see if I can improve the UX here a little.

**Comment by vapniks** [comment]
thankyou
